# Generated by Django 5.0.4 on 2024-05-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetfood', '0003_alter_order_complete_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streetfood.customer'),
        ),
    ]
